package com.mayeo.sudoku.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val ColorScheme.selectedBack: Color
@Composable
get() = if (isSystemInDarkTheme()) SelectedBackDark else SelectedBackLight

val ColorScheme.correctBack: Color
@Composable
get() = if(isSystemInDarkTheme()) CorrectBackDark else CorrectBackLight

val ColorScheme.hintedBack: Color
@Composable
get() = if(isSystemInDarkTheme()) HintedBackDark else HintedBackLight

val ColorScheme.incorrectBack: Color
@Composable
get() = if(isSystemInDarkTheme()) IncorrectBackDark else IncorrectBackLight

// https://material-foundation.github.io/material-theme-builder/

// Dark
val P80 = Color(0xFFffb787)
val S80 = Color(0xFF99d4a3)
val T80 = Color(0xFFafc6ff)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val SelectedBackDark = Color(0x34FFFFFF)
val CorrectBackDark = Color(0xFFC5E1A5)
val HintedBackDark = Color(0xFF90CAF9)
val IncorrectBackDark = Color(0xFFEF9A9A)

// Light
val P40 = Color(0xff8b4f24)
val S40 = Color(0xff326941)
val T40 = Color(0xff465d91)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val SelectedBackLight = Color(0x34000000)
val CorrectBackLight = Color(0xFF7CB342)
val HintedBackLight = Color(0xFF1E88E5)
val IncorrectBackLight = Color(0xFFE53935)


val primaryLight = Color(0xFF8B4F24)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC7)
val onPrimaryContainerLight = Color(0xFF311300)
val secondaryLight = Color(0xFF326941)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB4F1BD)
val onSecondaryContainerLight = Color(0xFF00210C)
val tertiaryLight = Color(0xFF465D91)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E2FF)
val onTertiaryContainerLight = Color(0xFF001943)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xFFF4DED3)
val onSurfaceVariantLight = Color(0xFF52443C)
val outlineLight = Color(0xFF84746A)
val outlineVariantLight = Color(0xFFD7C3B8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E29)
val inverseOnSurfaceLight = Color(0xFFFFEDE5)
val inversePrimaryLight = Color(0xFFFFB787)
val surfaceDimLight = Color(0xFFE7D7CE)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EA)
val surfaceContainerLight = Color(0xFFFCEBE2)
val surfaceContainerHighLight = Color(0xFFF6E5DC)
val surfaceContainerHighestLight = Color(0xFFF0DFD7)

val primaryLightMediumContrast = Color(0xFF69350A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA56537)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF124D27)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF488056)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF294274)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5C74A9)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F5)
val onBackgroundLightMediumContrast = Color(0xFF221A15)
val surfaceLightMediumContrast = Color(0xFFFFF8F5)
val onSurfaceLightMediumContrast = Color(0xFF221A15)
val surfaceVariantLightMediumContrast = Color(0xFFF4DED3)
val onSurfaceVariantLightMediumContrast = Color(0xFF4E4038)
val outlineLightMediumContrast = Color(0xFF6B5C53)
val outlineVariantLightMediumContrast = Color(0xFF88776E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382E29)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE5)
val inversePrimaryLightMediumContrast = Color(0xFFFFB787)
val surfaceDimLightMediumContrast = Color(0xFFE7D7CE)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1EA)
val surfaceContainerLightMediumContrast = Color(0xFFFCEBE2)
val surfaceContainerHighLightMediumContrast = Color(0xFFF6E5DC)
val surfaceContainerHighestLightMediumContrast = Color(0xFFF0DFD7)

val primaryLightHighContrast = Color(0xFF3B1900)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF69350A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002910)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF124D27)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002050)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF294274)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F5)
val onBackgroundLightHighContrast = Color(0xFF221A15)
val surfaceLightHighContrast = Color(0xFFFFF8F5)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF4DED3)
val onSurfaceVariantLightHighContrast = Color(0xFF2D221A)
val outlineLightHighContrast = Color(0xFF4E4038)
val outlineVariantLightHighContrast = Color(0xFF4E4038)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF382E29)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE8DB)
val surfaceDimLightHighContrast = Color(0xFFE7D7CE)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F5)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF1EA)
val surfaceContainerLightHighContrast = Color(0xFFFCEBE2)
val surfaceContainerHighLightHighContrast = Color(0xFFF6E5DC)
val surfaceContainerHighestLightHighContrast = Color(0xFFF0DFD7)

val primaryDark = Color(0xFFFFB787)
val onPrimaryDark = Color(0xFF502400)
val primaryContainerDark = Color(0xFF6E390E)
val onPrimaryContainerDark = Color(0xFFFFDCC7)
val secondaryDark = Color(0xFF99D4A3)
val onSecondaryDark = Color(0xFF003918)
val secondaryContainerDark = Color(0xFF17512B)
val onSecondaryContainerDark = Color(0xFFB4F1BD)
val tertiaryDark = Color(0xFFAFC6FF)
val onTertiaryDark = Color(0xFF132F60)
val tertiaryContainerDark = Color(0xFF2D4678)
val onTertiaryContainerDark = Color(0xFFD9E2FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120D)
val onBackgroundDark = Color(0xFFF0DFD7)
val surfaceDark = Color(0xFF19120D)
val onSurfaceDark = Color(0xFFF0DFD7)
val surfaceVariantDark = Color(0xFF52443C)
val onSurfaceVariantDark = Color(0xFFD7C3B8)
val outlineDark = Color(0xFF9F8D83)
val outlineVariantDark = Color(0xFF52443C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD7)
val inverseOnSurfaceDark = Color(0xFF382E29)
val inversePrimaryDark = Color(0xFF8B4F24)
val surfaceDimDark = Color(0xFF19120D)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A15)
val surfaceContainerDark = Color(0xFF261E19)
val surfaceContainerHighDark = Color(0xFF312823)
val surfaceContainerHighestDark = Color(0xFF3D332D)

val primaryDarkMediumContrast = Color(0xFFFFBC91)
val onPrimaryDarkMediumContrast = Color(0xFF290F00)
val primaryContainerDarkMediumContrast = Color(0xFFC68050)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF9DD9A7)
val onSecondaryDarkMediumContrast = Color(0xFF001B08)
val secondaryContainerDarkMediumContrast = Color(0xFF649D70)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB5CAFF)
val onTertiaryDarkMediumContrast = Color(0xFF001439)
val tertiaryContainerDarkMediumContrast = Color(0xFF7890C7)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF19120D)
val onBackgroundDarkMediumContrast = Color(0xFFF0DFD7)
val surfaceDarkMediumContrast = Color(0xFF19120D)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF8)
val surfaceVariantDarkMediumContrast = Color(0xFF52443C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDBC7BC)
val outlineDarkMediumContrast = Color(0xFFB29F95)
val outlineVariantDarkMediumContrast = Color(0xFF918076)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF312823)
val inversePrimaryDarkMediumContrast = Color(0xFF6F3A0F)
val surfaceDimDarkMediumContrast = Color(0xFF19120D)
val surfaceBrightDarkMediumContrast = Color(0xFF413731)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D08)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A15)
val surfaceContainerDarkMediumContrast = Color(0xFF261E19)
val surfaceContainerHighDarkMediumContrast = Color(0xFF312823)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D332D)

val primaryDarkHighContrast = Color(0xFFFFFAF8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBC91)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF0FFEE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9DD9A7)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFCFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB5CAFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF19120D)
val onBackgroundDarkHighContrast = Color(0xFFF0DFD7)
val surfaceDarkHighContrast = Color(0xFF19120D)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF52443C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF8)
val outlineDarkHighContrast = Color(0xFFDBC7BC)
val outlineVariantDarkHighContrast = Color(0xFFDBC7BC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF471F00)
val surfaceDimDarkHighContrast = Color(0xFF19120D)
val surfaceBrightDarkHighContrast = Color(0xFF413731)
val surfaceContainerLowestDarkHighContrast = Color(0xFF140D08)
val surfaceContainerLowDarkHighContrast = Color(0xFF221A15)
val surfaceContainerDarkHighContrast = Color(0xFF261E19)
val surfaceContainerHighDarkHighContrast = Color(0xFF312823)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3D332D)